apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-monitoring-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: n0tn1w/server-monitoring:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80